"""
Django settings for asm_backend project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import logging
from pathlib import Path
from decouple import config
from asm_backend.logFormatter import CustomJsonFormatter
from logging.handlers import RotatingFileHandler
from pathlib import Path
from django.utils.log import DEFAULT_LOGGING
import sentry_sdk

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sentry_sdk.init(
    dsn="https://f744327648541d6ab7c02c1e016dbc1c@o4506899332988928.ingest.us.sentry.io/4510221769965568",
    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
    send_default_pii=True,
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-j_$)e9u8$@^q_ac9h2#jqnhkhdqq^#n9=t0w)%%%51+73ia6fe"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

CORS_ALLOWED_ORIGINS = ["http://localhost:5173", "http://localhost:5174"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # django apps
    "apps.people",
    "apps.assets",
    "apps.licence",
    "apps.userActivities",
    # third party apps
    "rest_framework",
    "corsheaders",
    "drf_spectacular",
    "post_office",
    "django_celery_results",
    "django_celery_beat",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.userActivities.middleware.CaptureRequestMiddleware",
]

ROOT_URLCONF = "asm_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "asm_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": config("POSTGRES_ENGINE"),
        "NAME": config("POSTGRES_DB"),
        "USER": config("POSTGRES_USER"),
        "PASSWORD": config("POSTGRES_PASSWORD"),
        "HOST": config("POSTGRES_HOST"),
        "PORT": config("POSTGRES_PORT"),
    },
}


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": config("REDIS_HOST"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


AUTH_USER_MODEL = "people.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
}


SPECTACULAR_SETTINGS = {
    "TITLE": "ASM Backend",
    "DESCRIPTION": "This is an Asset Management backend",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


EMAIL_USE_TLS = config("EMAIL_USE_TLS")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT")
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_BACKEND = config("EMAIL_BACKEND")

CELERY_BROKER_URL = config("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND")
CELERY_TIME_ZONE = config("CELERY_TIME_ZONE")


LOG_DIR = Path("./logs")
LOG_DIR.mkdir(exist_ok=True)

LOG_LEVEL = "DEBUG" 


# Check if logging is already configured
if not logging.getLogger().handlers:

    # Define formatters
    formatter_console = logging.Formatter(
    "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - Line: %(lineno)d - %(message)s"
    )

    formatter_file = logging.Formatter(
        "%(asctime)s - PID: %(process)d - Thread: %(threadName)s - %(name)s - %(levelname)s - %(pathname)s - Line: %(lineno)d - %(message)s"
    )

    formatter_json = CustomJsonFormatter()
    formatter_django_server = DEFAULT_LOGGING["formatters"]["django.server"]

    # Create handlers
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter_console)

    file_handler = RotatingFileHandler(
        LOG_DIR / "asm.log", maxBytes=1024 * 1024 * 100, backupCount=7
    )
    file_handler.setFormatter(formatter_file)

    custom_logger_handler = RotatingFileHandler(
        LOG_DIR / "asm_custom.log", maxBytes=1024 * 1024 * 100, backupCount=7
    )
    custom_logger_handler.setFormatter(formatter_json)

    # Configure root logger
    root_logger = logging.getLogger()
    if not root_logger.handlers:  # Avoid duplicate handlers
        root_logger.setLevel(LOG_LEVEL)
        root_logger.addHandler(console_handler)
        root_logger.addHandler(file_handler)
        root_logger.addHandler(custom_logger_handler)
    
    loggers = {
        "apps": LOG_LEVEL,
        "django.server": LOG_LEVEL,
        "channels": LOG_LEVEL,
    }

    for logger_name, level in loggers.items():
        logger = logging.getLogger(logger_name)
        logger.setLevel(level)
        logger.addHandler(console_handler)
        logger.addHandler(file_handler)
        logger.addHandler(custom_logger_handler)

